# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 11:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('softlib', '0001_initial'),
        ('manager', '0002_auto_20170727_1953'),
    ]

    operations = [
        migrations.CreateModel(
            name='Java',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('prefix', models.CharField(default='/usr/local', max_length=100)),
                ('host', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='manager.Host')),
                ('softlib', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='softlib.Softlib')),
            ],
        ),
        migrations.CreateModel(
            name='MySQL',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('prefix', models.CharField(default='/usr/local', max_length=100)),
                ('passwd', models.CharField(default='000000', max_length=100)),
                ('port', models.IntegerField(default='3306')),
                ('socket', models.CharField(default='/tmp/mysql.sock', max_length=100)),
                ('datadir', models.CharField(default='/storage/mysql', max_length=100)),
                ('online', models.BooleanField(default=False)),
                ('host', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='manager.Host')),
                ('softlib', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='softlib.Softlib')),
            ],
        ),
        migrations.CreateModel(
            name='Nginx',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('prefix', models.CharField(default='/usr/local', max_length=100)),
                ('pid', models.CharField(max_length=100)),
                ('port', models.CharField(default='80', max_length=100)),
                ('online', models.BooleanField(default=False)),
                ('host', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='manager.Host')),
                ('softlib', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='softlib.Softlib')),
            ],
        ),
        migrations.CreateModel(
            name='Redis',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('prefix', models.CharField(default='/usr/local', max_length=100)),
                ('bind', models.CharField(default='0.0.0.0', max_length=100)),
                ('port', models.CharField(default='6379', max_length=100)),
                ('datadir', models.CharField(max_length=100)),
                ('requirepass', models.CharField(max_length=100)),
                ('online', models.BooleanField(default=False)),
                ('host', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='manager.Host')),
                ('softlib', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='softlib.Softlib')),
            ],
        ),
        migrations.CreateModel(
            name='Tomcat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('prefix', models.CharField(default='/usr/local', max_length=100)),
                ('java_opts', models.CharField(default='', max_length=100)),
                ('online', models.BooleanField(default=False)),
                ('host', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='manager.Host')),
                ('softlib', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='softlib.Softlib')),
            ],
        ),
    ]
