# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 08:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tomcat',
            name='online',
        ),
        migrations.AddField(
            model_name='tomcat',
            name='log',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tomcat',
            name='port',
            field=models.CharField(default='', max_length=6),
        ),
        migrations.AddField(
            model_name='tomcat',
            name='web_xml',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='tomcat',
            name='host',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='manager.Host'),
        ),
        migrations.AlterField(
            model_name='tomcat',
            name='prefix',
            field=models.CharField(default='', max_length=100),
        ),
    ]
