# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-05 03:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('img', models.CharField(default='user.jpg', max_length=10)),
            ],
        ),
    ]
