# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 11:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('systemtype', models.CharField(default='centos6.5', max_length=50)),
                ('manage_ip', models.CharField(default='10.100.100.246', max_length=15)),
                ('service_ip', models.CharField(default='10.100.100.246', max_length=15)),
                ('outer_ip', models.CharField(default='10.100.100.246', max_length=15)),
                ('server_position', models.CharField(default='Vmware', max_length=50)),
                ('hostname', models.CharField(default='localhost', max_length=50)),
                ('normal_user', models.CharField(default='QbDev', max_length=15)),
                ('sshpasswd', models.CharField(default='000000', max_length=100)),
                ('sshport', models.CharField(default='52000', max_length=5)),
                ('coreness', models.IntegerField(default=2)),
                ('memory', models.IntegerField(default=2048)),
                ('root_disk', models.IntegerField(default=20)),
                ('share_disk_path', models.CharField(max_length=200)),
                ('share_disk', models.IntegerField(default=30)),
                ('info', models.CharField(default='\u65e0\u4fe1\u606f', max_length=200)),
                ('group', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='host_set', to='manager.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('disk_size', models.CharField(default='0G', max_length=100)),
                ('disk_path', models.CharField(default='//10.100.100.246/storage', max_length=100)),
                ('info', models.CharField(default='NoUse', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='host',
            name='storages',
            field=models.ManyToManyField(related_name='storage_set', to='manager.Storage'),
        ),
    ]
