# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='info',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
