# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 08:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20170727_1953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='share_disk',
        ),
        migrations.RemoveField(
            model_name='host',
            name='share_disk_path',
        ),
    ]
