# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 00:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_auto_20170728_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='storage_set', to='manager.Group'),
        ),
    ]
