# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 11:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_auto_20170719_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='group_id', to='manager.Group'),
        ),
    ]
