# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 03:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_storage_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='manager.Group'),
        ),
        migrations.AlterField(
            model_name='host',
            name='storages',
            field=models.ManyToManyField(to='manager.Storage'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='manager.Group'),
        ),
    ]
