# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 07:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_auto_20170719_1946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='remark',
            new_name='info',
        ),
        migrations.RenameField(
            model_name='host',
            old_name='name',
            new_name='hostname',
        ),
        migrations.RemoveField(
            model_name='host',
            name='sship',
        ),
        migrations.AddField(
            model_name='host',
            name='coreness',
            field=models.IntegerField(default=2, max_length=5),
        ),
        migrations.AddField(
            model_name='host',
            name='info',
            field=models.CharField(default='\u65e0\u7528\u9014', max_length=200),
        ),
        migrations.AddField(
            model_name='host',
            name='manage_ip',
            field=models.CharField(default='10.100.100.246', max_length=15),
        ),
        migrations.AddField(
            model_name='host',
            name='memory',
            field=models.IntegerField(default=2048, max_length=10),
        ),
        migrations.AddField(
            model_name='host',
            name='normal_user',
            field=models.CharField(default='QbDev', max_length=15),
        ),
        migrations.AddField(
            model_name='host',
            name='outer_ip',
            field=models.CharField(default='10.100.100.246', max_length=15),
        ),
        migrations.AddField(
            model_name='host',
            name='root_disk',
            field=models.IntegerField(default=20, max_length=10),
        ),
        migrations.AddField(
            model_name='host',
            name='server_position',
            field=models.CharField(default='Vmware', max_length=50),
        ),
        migrations.AddField(
            model_name='host',
            name='service_ip',
            field=models.CharField(default='10.100.100.246', max_length=15),
        ),
        migrations.AddField(
            model_name='host',
            name='share_disk',
            field=models.IntegerField(default=30, max_length=10),
        ),
        migrations.AddField(
            model_name='host',
            name='share_disk_path',
            field=models.CharField(default='//10.100.100.246', max_length=200),
        ),
        migrations.AddField(
            model_name='host',
            name='systemtype',
            field=models.CharField(default='centos6.5', max_length=50),
        ),
        migrations.AlterField(
            model_name='host',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='host_set', to='manager.Group'),
        ),
        migrations.AlterField(
            model_name='host',
            name='sshport',
            field=models.CharField(default='52000', max_length=5),
        ),
    ]
