# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_auto_20170801_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='coreness',
            field=models.CharField(default='2', max_length=5),
        ),
        migrations.AlterField(
            model_name='host',
            name='memory',
            field=models.CharField(default='2048M', max_length=7),
        ),
        migrations.AlterField(
            model_name='host',
            name='root_disk',
            field=models.CharField(default='30G', max_length=7),
        ),
    ]
