# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 08:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_auto_20170801_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storage',
            name='group',
        ),
    ]
