# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_auto_20170721_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='coreness',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='host',
            name='memory',
            field=models.IntegerField(default=2048),
        ),
        migrations.AlterField(
            model_name='host',
            name='root_disk',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='host',
            name='share_disk',
            field=models.IntegerField(default=30),
        ),
    ]
