# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_auto_20170721_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='info',
            field=models.CharField(default='No Use', max_length=200),
        ),
    ]
