# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_auto_20170804_1853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='group',
        ),
        migrations.AddField(
            model_name='host',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='hosts', to='manager.Group', verbose_name='_Group'),
        ),
        migrations.AlterField(
            model_name='group',
            name='info',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='host',
            name='coreness',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='host',
            name='info',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='host',
            name='manage_ip',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='host',
            name='memory',
            field=models.CharField(default='', max_length=7),
        ),
        migrations.AlterField(
            model_name='host',
            name='normal_user',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='host',
            name='outer_ip',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='host',
            name='root_disk',
            field=models.CharField(default='', max_length=7),
        ),
        migrations.AlterField(
            model_name='host',
            name='server_position',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='host',
            name='service_ip',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='host',
            name='sshpasswd',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='host',
            name='systemtype',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='storage',
            name='disk_path',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='storage',
            name='disk_size',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='storage',
            name='info',
            field=models.CharField(default='', max_length=100),
        ),
    ]
