# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 00:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_auto_20170807_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='storages',
            field=models.ManyToManyField(blank=True, related_name='hosts', to='manager.Storage', verbose_name='Host'),
        ),
    ]
