# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0010_auto_20170808_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='systemtype',
            field=models.IntegerField(choices=[(0, ''), (1, 'Windows Server 2006'), (2, 'Windows Server 2008'), (3, 'Centos 6.5'), (4, 'Centos 7.1')], default=0),
        ),
    ]
