# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0012_auto_20170808_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='hosts', to='manager.Group', verbose_name='Group'),
        ),
    ]
