# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0013_auto_20170808_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='manage_ip',
            field=models.CharField(default='\u65e0', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='outer_ip',
            field=models.CharField(default='\u65e0', max_length=15, null=True),
        ),
    ]
