# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 03:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0014_auto_20170810_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='manage_ip',
            field=models.CharField(default='', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='outer_ip',
            field=models.CharField(default='', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='systemtype',
            field=models.IntegerField(choices=[(0, '\u672a\u6dfb\u52a0'), (1, 'Windows Server 2006'), (2, 'Windows Server 2008'), (3, 'Centos 6.5'), (4, 'Centos 7.1')], default=0),
        ),
    ]
