# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-22 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0015_auto_20170811_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='hostname',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='host',
            name='sshport',
            field=models.CharField(default='', max_length=5),
        ),
    ]
