# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-04 03:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0017_auto_20170822_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='hostname',
            field=models.CharField(default='localhost.localdomain', max_length=50),
        ),
    ]
