# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-12 00:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0018_auto_20170904_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='groups', to='manager.Group', verbose_name='Groups'),
        ),
    ]
