# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-12 00:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0019_storage_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storage',
            name='groups',
        ),
    ]
