# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-13 01:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('timeline', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Callback',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('info', models.TextField()),
                ('history', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='callback', to='timeline.History')),
            ],
        ),
    ]
