# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 03:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='noName', max_length=100)),
                ('info', models.CharField(default='noUse', max_length=100)),
                ('script', models.TextField()),
                ('author', models.CharField(default='noAuthor', max_length=100)),
            ],
        ),
    ]
