# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-12 11:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manager', '0020_remove_storage_groups'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayBook',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='noName', max_length=100)),
                ('info', models.CharField(default='noUse', max_length=100)),
                ('sort', models.IntegerField(default=0)),
                ('sudo', models.IntegerField(choices=[(0, '\u4e0d\u9700\u8981'), (1, '\u9700\u8981')], default=1)),
                ('status', models.IntegerField(choices=[(0, '\u672a\u5b8c\u6210'), (1, '\u5df2\u5b8c\u6210')], default=0)),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='puser', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, related_name='playbooks', to='manager.Group', verbose_name='Playbook')),
            ],
        ),
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='noName', max_length=100)),
                ('info', models.CharField(default='noUse', max_length=100)),
                ('script', models.TextField(default='')),
                ('status', models.IntegerField(choices=[(0, '\u672a\u5b8c\u6210'), (1, '\u5df2\u5b8c\u6210')], default=0)),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='suser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ScriptArgs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('args_name', models.CharField(default='', max_length=100)),
                ('args_value', models.CharField(default='', max_length=100)),
                ('script', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='scriptargs', to='operation.Script')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mudule', models.CharField(default='hostname', max_length=20)),
                ('args', models.CharField(default='', max_length=100)),
                ('sort', models.IntegerField(default=0)),
                ('playbook', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='operation.PlayBook')),
            ],
        ),
    ]
