# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 10:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_auto_20170815_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scriptargs',
            name='script',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='scriptargs', to='operation.Script'),
        ),
    ]
