# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0008_script_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='status',
            field=models.IntegerField(choices=[(0, '\u672a\u5b8c\u6210'), (1, '\u5df2\u5b8c\u6210')], default=0),
        ),
    ]
