# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-06 07:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0009_script_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='suser', to=settings.AUTH_USER_MODEL),
        ),
    ]
