# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-06 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0010_auto_20170906_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayBook',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='noName', max_length=100)),
                ('info', models.CharField(default='noUse', max_length=100)),
                ('status', models.IntegerField(choices=[(0, '\u672a\u5b8c\u6210'), (1, '\u5df2\u5b8c\u6210')], default=0)),
            ],
        ),
    ]
