# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-06 07:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0011_playbook'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adhoc',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('module', models.CharField(default='hostname', max_length=20)),
                ('args', models.CharField(default='', max_length=100)),
                ('sort', models.IntegerField(default=0)),
                ('playbook', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ahocs', to='operation.PlayBook')),
            ],
        ),
    ]
