# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-06 08:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0013_playbook_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adhoc',
            name='playbook',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='adhocs', to='operation.PlayBook'),
        ),
    ]
