# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-07 01:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0014_auto_20170906_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='playbook',
            name='sudo',
            field=models.BooleanField(default=True),
        ),
    ]
