# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-07 01:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0015_playbook_sudo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playbook',
            name='sudo',
            field=models.IntegerField(choices=[(0, '\u4e0d\u9700\u8981'), (1, '\u9700\u8981')], default=1),
        ),
    ]
