# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-07 08:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0016_auto_20170907_0940'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adhoc',
            old_name='module',
            new_name='mudule',
        ),
    ]
