# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-07 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0017_auto_20170907_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='playbook',
            name='sort',
            field=models.IntegerField(default=0),
        ),
    ]
