# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-08 02:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0018_playbook_sort'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mudule', models.CharField(default='hostname', max_length=20)),
                ('args', models.CharField(default='', max_length=100)),
                ('sort', models.IntegerField(default=0)),
                ('playbook', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='operation.PlayBook')),
            ],
        ),
        migrations.RemoveField(
            model_name='adhoc',
            name='playbook',
        ),
        migrations.DeleteModel(
            name='Adhoc',
        ),
    ]
