# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-08 02:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0018_auto_20170904_1117'),
        ('operation', '0019_auto_20170908_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='playbook',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='playbooks', to='manager.Group'),
        ),
    ]
