# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-08 03:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0018_auto_20170904_1117'),
        ('operation', '0020_playbook_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playbook',
            name='group',
        ),
        migrations.AddField(
            model_name='playbook',
            name='group',
            field=models.ManyToManyField(blank=True, related_name='playbooks', to='manager.Group', verbose_name='Playbook'),
        ),
    ]
