# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-08 07:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0021_auto_20170908_1109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playbook',
            old_name='group',
            new_name='groups',
        ),
    ]
