# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-12 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Softlib',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('soft_type', models.CharField(choices=[(0, 'no'), (1, 'tomcat'), (2, 'db'), (3, 'redis'), (4, 'nginx'), (5, 'rabbitmq')], default=0, max_length=100)),
                ('soft_version', models.CharField(max_length=10)),
            ],
        ),
    ]
