# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 02:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anweb', '0002_auto_20170319_0225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='host',
            old_name='softlib_id',
            new_name='softlib',
        ),
    ]
