# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-03 13:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anweb', '0004_auto_20170330_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='softlib',
        ),
        migrations.RemoveField(
            model_name='host',
            name='state',
        ),
        migrations.RemoveField(
            model_name='java',
            name='group_id',
        ),
        migrations.RemoveField(
            model_name='mysql',
            name='extend',
        ),
        migrations.RemoveField(
            model_name='mysql',
            name='group_id',
        ),
        migrations.RemoveField(
            model_name='mysql',
            name='key_buffer_size',
        ),
        migrations.RemoveField(
            model_name='mysql',
            name='query_cache_size',
        ),
        migrations.RemoveField(
            model_name='mysql',
            name='read_buffer_size',
        ),
        migrations.RemoveField(
            model_name='mysql',
            name='read_rnd_buffer_size',
        ),
        migrations.RemoveField(
            model_name='mysql',
            name='server_id',
        ),
        migrations.RemoveField(
            model_name='mysql',
            name='sort_buffer_size',
        ),
        migrations.RemoveField(
            model_name='mysql',
            name='table_open_cache',
        ),
        migrations.RemoveField(
            model_name='mysql',
            name='thread_cache_size',
        ),
        migrations.RemoveField(
            model_name='nginx',
            name='group_id',
        ),
        migrations.RemoveField(
            model_name='nginx',
            name='locations',
        ),
        migrations.RemoveField(
            model_name='nginx',
            name='servername',
        ),
        migrations.RemoveField(
            model_name='nginx',
            name='workconn',
        ),
        migrations.RemoveField(
            model_name='nginx',
            name='workproc',
        ),
        migrations.RemoveField(
            model_name='redis',
            name='appendonly',
        ),
        migrations.RemoveField(
            model_name='redis',
            name='cluster_config_file',
        ),
        migrations.RemoveField(
            model_name='redis',
            name='cluster_enabled',
        ),
        migrations.RemoveField(
            model_name='redis',
            name='extend',
        ),
        migrations.RemoveField(
            model_name='redis',
            name='group_id',
        ),
        migrations.RemoveField(
            model_name='redis',
            name='masterauth',
        ),
        migrations.RemoveField(
            model_name='redis',
            name='noonrewrite',
        ),
        migrations.RemoveField(
            model_name='redis',
            name='saveoptions',
        ),
        migrations.RemoveField(
            model_name='redis',
            name='slaveof',
        ),
        migrations.RemoveField(
            model_name='tomcat',
            name='group_id',
        ),
        migrations.AddField(
            model_name='java',
            name='host',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='anweb.Host'),
        ),
        migrations.AddField(
            model_name='java',
            name='softlib',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='anweb.Softlib'),
        ),
        migrations.AddField(
            model_name='mysql',
            name='host',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='anweb.Host'),
        ),
        migrations.AddField(
            model_name='mysql',
            name='softlib',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='anweb.Softlib'),
        ),
        migrations.AddField(
            model_name='nginx',
            name='host',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='anweb.Host'),
        ),
        migrations.AddField(
            model_name='nginx',
            name='softlib',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='anweb.Softlib'),
        ),
        migrations.AddField(
            model_name='redis',
            name='host',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='anweb.Host'),
        ),
        migrations.AddField(
            model_name='redis',
            name='softlib',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='anweb.Softlib'),
        ),
        migrations.AddField(
            model_name='tomcat',
            name='host',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='anweb.Host'),
        ),
        migrations.AddField(
            model_name='tomcat',
            name='softlib',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='anweb.Softlib'),
        ),
        migrations.AlterField(
            model_name='host',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='anweb.Group'),
        ),
        migrations.AlterField(
            model_name='mysql',
            name='datadir',
            field=models.CharField(default='/storage/mysql', max_length=100),
        ),
        migrations.AlterField(
            model_name='nginx',
            name='prefix',
            field=models.CharField(default='/usr/local', max_length=100),
        ),
    ]
