# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-03 16:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anweb', '0005_auto_20170503_1322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='group_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='host',
            old_name='hostname',
            new_name='name',
        ),
    ]
