# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-03 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anweb', '0006_auto_20170503_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='name',
            field=models.CharField(default='localhost', max_length=50),
        ),
    ]
