# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-08 14:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anweb', '0009_auto_20170507_1456'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mysql',
            old_name='mysqlpasswd',
            new_name='passwd',
        ),
    ]
