# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-10 23:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anweb', '0011_auto_20170509_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='oper_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
