# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-12 10:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manager', '0020_remove_storage_groups'),
        ('softlib', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DB',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('prefix', models.CharField(default='/usr/local/mysql', max_length=100)),
                ('root_passwd', models.CharField(default='000000', max_length=100)),
                ('normal_user', models.CharField(default='NorUser', max_length=100)),
                ('normal_passwd', models.CharField(default='000000', max_length=100)),
                ('port', models.IntegerField(default='3306')),
                ('socket', models.CharField(default='/tmp/mysql.sock', max_length=100)),
                ('datadir', models.CharField(default='/storage/mysql', max_length=100)),
                ('host', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='manager.Host')),
                ('softlib', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='softlib.Softlib')),
            ],
        ),
    ]
