# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 13:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=100)),
                ('remark', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anweb.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Java',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('prefix', models.CharField(max_length=100)),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anweb.Group')),
            ],
        ),
        migrations.CreateModel(
            name='MySQL',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('prefix', models.CharField(max_length=100)),
                ('mysqlpasswd', models.CharField(max_length=100)),
                ('port', models.IntegerField(max_length=10)),
                ('socket', models.CharField(max_length=100)),
                ('datadir', models.CharField(max_length=100)),
                ('key_buffer_size', models.CharField(max_length=100)),
                ('table_open_cache', models.CharField(max_length=100)),
                ('sort_buffer_size', models.CharField(max_length=100)),
                ('read_buffer_size', models.CharField(max_length=100)),
                ('read_rnd_buffer_size', models.CharField(max_length=100)),
                ('query_cache_size', models.CharField(max_length=100)),
                ('thread_cache_size', models.CharField(max_length=100)),
                ('server_id', models.IntegerField(max_length=10)),
                ('extend', models.CharField(max_length=100)),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anweb.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Nginx',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('prefix', models.CharField(max_length=100)),
                ('workproc', models.CharField(max_length=100)),
                ('pid', models.CharField(max_length=100)),
                ('workconn', models.CharField(max_length=100)),
                ('port', models.CharField(max_length=100)),
                ('servername', models.CharField(max_length=100)),
                ('locations', models.CharField(max_length=100)),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anweb.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Redis',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('prefix', models.CharField(max_length=100)),
                ('bind', models.CharField(max_length=100)),
                ('port', models.CharField(max_length=100)),
                ('appendonly', models.CharField(max_length=100)),
                ('noonrewrite', models.CharField(max_length=100)),
                ('saveoptions', models.CharField(max_length=100)),
                ('datadir', models.CharField(max_length=100)),
                ('requirepass', models.CharField(max_length=100)),
                ('slaveof', models.CharField(max_length=100)),
                ('masterauth', models.CharField(max_length=100)),
                ('cluster_enabled', models.CharField(max_length=100)),
                ('cluster_config_file', models.CharField(max_length=100)),
                ('extend', models.CharField(max_length=100)),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anweb.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Soft',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('soft_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Softlib',
            fields=[
                ('id', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('soft_version', models.CharField(max_length=10)),
                ('soft_md5', models.CharField(max_length=100)),
                ('soft_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anweb.Soft')),
            ],
        ),
        migrations.CreateModel(
            name='Tomcat',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('prefix', models.CharField(max_length=100)),
                ('java_opts', models.CharField(max_length=100)),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anweb.Group')),
            ],
        ),
        migrations.AddField(
            model_name='host',
            name='softlib_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anweb.Softlib'),
        ),
    ]
