# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 02:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anweb', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='host',
            old_name='group_id',
            new_name='group',
        ),
    ]
