# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anweb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mysql',
            name='server_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='softlib',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
