# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anweb', '0002_auto_20170210_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mysql',
            name='port',
            field=models.IntegerField(),
        ),
    ]
