# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 19:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anweb', '0003_auto_20170319_0227'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('oper_time', models.DateField()),
                ('oper_info', models.CharField(max_length=100)),
                ('oper_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anweb.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('oper_name', models.CharField(default=0, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='history',
            name='oper_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anweb.Operation'),
        ),
    ]
