# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anweb', '0003_auto_20170210_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='sship',
            field=models.CharField(default='192.168.1.1', max_length=15),
        ),
        migrations.AddField(
            model_name='host',
            name='sshpasswd',
            field=models.CharField(default='000000', max_length=100),
        ),
        migrations.AddField(
            model_name='host',
            name='sshport',
            field=models.CharField(default='22', max_length=5),
        ),
    ]
