# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anweb', '0006_auto_20170210_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='java',
            name='prefix',
            field=models.CharField(default='/usr/local', max_length=100),
        ),
        migrations.AlterField(
            model_name='mysql',
            name='mysqlpasswd',
            field=models.CharField(default='000000', max_length=100),
        ),
        migrations.AlterField(
            model_name='mysql',
            name='port',
            field=models.IntegerField(default='3306'),
        ),
        migrations.AlterField(
            model_name='mysql',
            name='prefix',
            field=models.CharField(default='/usr/local', max_length=100),
        ),
        migrations.AlterField(
            model_name='mysql',
            name='socket',
            field=models.CharField(default='/tmp/mysql.sock', max_length=100),
        ),
        migrations.AlterField(
            model_name='nginx',
            name='port',
            field=models.CharField(default='80', max_length=100),
        ),
        migrations.AlterField(
            model_name='redis',
            name='bind',
            field=models.CharField(default='0.0.0.0', max_length=100),
        ),
        migrations.AlterField(
            model_name='redis',
            name='cluster_config_file',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='redis',
            name='cluster_enabled',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='redis',
            name='extend',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='redis',
            name='masterauth',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='redis',
            name='port',
            field=models.CharField(default='6379', max_length=100),
        ),
        migrations.AlterField(
            model_name='redis',
            name='prefix',
            field=models.CharField(default='/usr/local', max_length=100),
        ),
        migrations.AlterField(
            model_name='redis',
            name='slaveof',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='tomcat',
            name='java_opts',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='tomcat',
            name='prefix',
            field=models.CharField(default='/usr/local', max_length=100),
        ),
    ]
