# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 15:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anweb', '0007_auto_20170210_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='softlib_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='anweb.Softlib'),
        ),
    ]
