# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anweb', '0008_auto_20170210_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('state_name', models.CharField(default='\u672a\u90e8\u7f72', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='host',
            name='state',
            field=models.IntegerField(default=0),
        ),
    ]
