# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-04 01:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.IntegerField(choices=[(0, '\u8d44\u4ea7\u7ba1\u7406'), (1, '\u811a\u672c\u64cd\u4f5c'), (2, '\u8fd0\u7ef4\u64cd\u4f5c')], default=0)),
                ('info', models.TextField(default='')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='startuser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
