# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-12 11:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manager', '0020_remove_storage_groups'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.IntegerField(choices=[(0, '\u8d44\u4ea7\u7ba1\u7406'), (1, '\u811a\u672c\u4fee\u6539'), (2, '\u5267\u672c\u4fee\u6539'), (3, '\u8fd0\u7ef4\u64cd\u4f5c'), (4, '\u4eba\u5458\u7ba1\u7406')], default=0)),
                ('info', models.TextField(default='')),
                ('status', models.IntegerField(choices=[(0, '\u6b63\u5728\u8fd0\u884c'), (1, '\u8fd0\u884c\u6210\u529f'), (2, '\u8fd0\u884c\u5931\u8d25')], default=0)),
                ('starttime', models.DateTimeField(auto_now_add=True)),
                ('endtime', models.DateTimeField(auto_now=True)),
                ('hosts', models.ManyToManyField(blank=True, related_name='hosts', to='manager.Host', verbose_name='Host')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='startuser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
