# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-04 02:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0002_history_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='starttime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
