# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-04 02:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0003_history_starttime'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='endtime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
