# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-05 09:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0006_remove_history_hosts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='user',
        ),
    ]
