# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-05 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0018_auto_20170904_1117'),
        ('timeline', '0008_history_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='hosts',
            field=models.ManyToManyField(blank=True, related_name='hosts', to='manager.Host', verbose_name='Host'),
        ),
    ]
