# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-06 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0010_auto_20170906_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='type',
            field=models.IntegerField(choices=[(0, '\u8d44\u4ea7\u7ba1\u7406'), (1, '\u811a\u672c\u4fee\u6539'), (2, '\u5267\u672c\u4fee\u6539'), (3, '\u8fd0\u7ef4\u64cd\u4f5c')], default=0),
        ),
    ]
